# Creating synthetic attrition data with the Python Faker library for attrition predictive modelling

For predictive modeling purposes, the dataset will need predictors and a target feature.

Predictors:
- department (HR, Finance, Marketing, Sales, IT, Customer Service, Legal, Project Management)
- province (in Canada)
- hierarchy level (individual contributor, manager/director, senior leadership)
- tenure with the current company (in years)
- hiring source (agency, direct, employee referral)
- gender (male, female, non-binary)
- ethnicity (caucasian, african descent, indigenous, bi-racial, hispanic, pacific islander, middle eastern, asian)

Target: whether the employee resigned

In [4]:
# importing data creation libraries
from faker import Faker
from faker.providers import DynamicProvider
from random import choices
import random
from datetime import datetime, timedelta

# data manipulation & analysis libraries
import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis

# data visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# creating a Canadian Faker instance
fake= Faker(locale= 'en_CA')

In [5]:
# creating the list of hierarchy levels with their weights
hierarchy = {
    "Support": 0.07,
    "Professional": 0.72,
    "Director": 0.16,
    "Executive": 0.05
}

# creating the list of genders with their weights
genders = {
    "Man": 0.4921,
    "Woman": 0.5066,
    "Person": 0.0013
}

# creating the weights for the provinces
province_pool = ['Alberta', 'British Columbia', 'Manitoba', 'New Brunswick',
                 'Newfoundland and Labrador', 'Northwest Territories',
                 'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island',
                 'Quebec', 'Saskatchewan', 'Yukon']
province_acronyms = ['AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON',
                     'PE', 'QC', 'SK', 'YT']
province_with_acronyms = list(zip(province_pool, province_acronyms))
province_weights = [0.1184, 0.1380, 0.0362, 0.0207, 0.0132, 0.0011, 0.0261,
                    0.0011, 0.3905, 0.0043, 0.2193, 0.0300, 0.0011]

# creating the list of ethnicities with their weights
ethnicities = {
    "Caucasian": 0.656,
    "African descent": 0.043,
    "Indigenous": 0.05,
    "Bi-racial": 0.03,
    "Hispanic": 0.016,
    "Pacific Islander": 0.026,
    "Middle Eastern": 0.019,
    "Asian": 0.16
}

# creating employee types with their weights
ee_types = {
    "Full Time - Regular": 0.97,
    "Full Time - Temporary": 0.01,
    "Part Time - Regular": 0.01,
    "Part Time - Temporary": 0.01
}

# creating the list of hiring sources with their weights
sources = {
    "agency": 0.2,
    "direct": 0.5,
    "referral": 0.3
}

# creating the list of departments
department_pool = ["Human Capital Strategy", "Financial Strategy & Analysis",
                   "Communications & Brand Strategy", "Service Delivery & Operations",
                   "Technology Solutions & Services", "Client Experience & Engagement",
                   "Regulatory Compliance & Risk Management", "Portfolio Management & Execution",
                   "Corporate Services & Solutions"]
department_acronyms = ["HCS", "FSA", "CBS", "SDO", "TSS", "CEE", "RCRM", "PME", "CSS"]
department_with_acronyms = list(zip(department_pool, department_acronyms))

In the separate file 'job_titles', sample job titles were compiled per hierarchy level and department in the format of the examples below.
<table>
    <tr>
        <th>Department</th>
        <th>Hierarchy Level</th>
        <th>Job Title</th>
    </tr>
    <tr>
        <td>Corporate Services & Solutions</td>
        <td>Support</td>
        <td>Receptionist</td>
    </tr>
    <tr>
        <td>Client Experience & Engagement</td>
        <td>Professional</td>
        <td>Account Manager</td>
    </tr>
    <tr>
        <td>Human Capital Strategy</td>
        <td>Director</td>
        <td>Director of Talent Acquisition</td>
    </tr>
    <tr>
        <td>Financial Strategy & Analysis</td>
        <td>Executive</td>
        <td>Executive Director of Finance</td>
    </tr> 
</table>

In [7]:
# loading the job titles into a dataframe
job_titles = pd.read_csv('attrition_companion_files/job_titles.csv')
job_titles.sample(5)

,Department,Hierarchy Level,Job Title
70,Service Delivery & Operations,Director,Director of Service Delivery
66,Service Delivery & Operations,Professional,Operations Supervisor
64,Service Delivery & Operations,Professional,Operations Manager
99,Corporate Services & Solutions,Support,Administrative Assistant
50,Communications & Brand Strategy,Director,Director of Marketing Communications

In the separate file 'province_cities', sample cities per province have been compiled to serve as work locations. 
5 cities are provided for the biggest provinces, 3 for medium provinces and the capital for small provinces.
<table>
    <tr>
        <th>Province</th>
        <th>Cities</th>
    </tr>
    <tr>
        <td>Ontario</td>
        <td>Toronto, Ottawa, Mississauga, Brampton, Hamilton</td>
    </tr>
    <tr>
        <td>Alberta</td>
        <td>Calgary, Edmonton, Red Deer</td>
    </tr>
    <tr>
        <td>Nova Scotia</td>
        <td>Halifax</td>
   </tr> 
</table>

In [9]:
# loading the cities into a dataframe
cities = pd.read_csv('attrition_companion_files/cities.csv')
cities.sample(5)

            Province         City
6             Quebec  Quebec City
17     New Brunswick  Fredericton
1            Ontario       Ottawa
2            Ontario  Mississauga
13  British Columbia    Vancouver

In [10]:
# defining a function to generate random date between two dates
def random_between_dates(start, end):
    delta = end - start
    random_point = random.randint(0, delta.days)
    return start + timedelta(days= random_point)

# defining a function to calculate age either at time of departure or now
def calcul_age(birth_date, reference_date):
    return reference_date.year - birth_date.year - \
            ((reference_date.month, reference_date.day) < \
             (birth_date.month, birth_date.day))

# defining a function to extract a random job title with department + level
def get_job_title(department, hierarchy_level):
    filtered_df = job_titles[(job_titles['Department'] == department) & (job_titles['Hierarchy Level'] == hierarchy_level)]
    if not filtered_df.empty:
        return random.choice(filtered_df['Job Title'].tolist())
    else:
        return 'Invalid department or hierarchy level.'

# defining a function to extract a random city per province
def get_city(province):
    filtered_df = cities[cities['Province'] == province]
    if not filtered_df.empty:
        return random.choice(filtered_df['City'].tolist())
    else:
        return 'Invalid province.'

# defining constants
_year = 365.25 # days, as we're taking into account leap years
_current_date = datetime.now()
_weeks_perYear = 52

In [11]:
# creating a function to generate employee records
def create_employees(num_employees):
    employee_list = []
    for i in range(num_employees):
        employee = {}
        employee['ee#'] = 10000000+i
        employee['first_name'] = fake.first_name()
        employee['last_name'] = fake.last_name()
        employee['full_name'] = f"{employee['last_name']}, {employee['first_name']}"
          
        # instancing random choices for DEI variables
        level = random.choices(population= list(hierarchy.keys()),
                               weights= list(hierarchy.values()),
                               k= 1)[0]
        department, d_acronym = random.choices(department_with_acronyms,
                                               k= 1)[0]
        position = get_job_title(department, level)
        type = random.choices(population= list(ee_types.keys()),
                              weights= list(ee_types.values()),
                              k= 1)[0]
        gender = random.choices(population= list(genders.keys()),
                               weights= list(genders.values()),
                               k= 1)[0]
        ethnicity = random.choices(population= list(ethnicities.keys()),
                                   weights= list(ethnicities.values()),
                                   k= 1)[0]
        source = random.choices(population= list(sources.keys()),
                                weights= list(sources.values()),
                                k= 1)[0]
        province, p_acronym = random.choices(province_with_acronyms,
                                           weights= province_weights,
                                           k= 1)[0]
        work_location = get_city(province)
        
        # generating appropriate birth dates
        birth_date = random_between_dates(
            _current_date - timedelta(days= _year * 100),
            _current_date)

        # generating appropriate dates
        '''
        birth date is generated first to serve as a base from a range of 100 years.
        based on birth date, a start date is generated for the employee to be between
        25 and 60 years old when joining the company.
        if the generated start date is beyond current date, it is regenerated to ensure
        that it stays in the past, though that limit can be modified. 
        
        based on start date, a termination date is generated with a lower bound equal
        to the start date (the employee resigned same day as they started) and an upper
        bound either equal to the current date (which will be transformed as none) or
        retirement age defined by tenure <= 40 years or age <= 70.
        to ensure enough employees are active while maintaining retirement restrictions
        a random probability is then applied to nullify the term date.
        '''
        
        while True:
            try:
                birth_date = random_between_dates(
                            _current_date - timedelta(days= _year * 100),
                            _current_date)
                min_start_date = birth_date + timedelta(days= _year*25)
                max_start_date = min(_current_date,
                             birth_date + timedelta(days= _year*60))
                start_date = random_between_dates(min_start_date, 
                                                  max_start_date)
                if start_date > _current_date:
                    raise ValueError
                min_term_date = start_date
                max_term_date = min(_current_date,
                                    start_date + timedelta(days=_year*40),
                                    birth_date + timedelta(days=_year*70))
                term_date = random_between_dates(min_term_date,
                                                 max_term_date)
                if term_date == _current_date:
                    term_date = None
                # having a ratio of 60/40 active/terminated employees
                generate_term = random.choices([True, False],
                                               weights= [20,80],
                                               k= 1)[0]
                if not generate_term:
                    potential_tenure = (_current_date - start_date).days \
                                        // _year
                    potential_age = (_current_date - birth_date).days \
                                        // _year
                    if potential_tenure <= 40 and potential_age <= 70:
                        term_date = None
                break
            except ValueError:
                continue
                    
        # calculating tenure
        if term_date is None:
            tenure = (_current_date - start_date).days / _year
        else:
            tenure = (term_date - start_date).days / _year
        tenure = round(tenure, 1)
        
        # calculating age at time of departure if terminated
        if term_date is None:
            age = (_current_date - birth_date).days / _year
        else:
            age = (term_date - birth_date).days / _year
        age = round(age, 1)
              
        # instancing the dataframe's columns
        employee['position'] = position
        employee['position_type'] = type
        employee['start_date'] = start_date.strftime('%Y-%m-%d')
        employee['term_date'] = term_date.strftime('%Y-%m-%d') if term_date else term_date
        employee['tenure'] = tenure
        employee['birth_date'] = birth_date.strftime('%Y-%m-%d')
        employee['age'] = age
        employee['department'] = department
        employee['dpt_acronym'] = d_acronym
        employee['work_location'] = work_location
        employee['employment_province'] = province
        employee['province_acronym'] = p_acronym
        employee['hire_source'] = source
        employee['level'] = level
        employee['gender'] = gender
        employee['ethnicity'] = ethnicity
        employee_list.append(employee)
    return pd.DataFrame(employee_list)

In [12]:
# creating a dataframe to hold the output of the function
# and visualize it to check for correct output
attrition = create_employees(2000000)
print(attrition.shape)
print(attrition.columns)
attrition.sample(n=5)

(2000000, 20)
Index(['ee#', 'first_name', 'last_name', 'full_name', 'position',
       'position_type', 'start_date', 'term_date', 'tenure', 'birth_date',
       'age', 'department', 'dpt_acronym', 'work_location',
       'employment_province', 'province_acronym', 'hire_source', 'level',
       'gender', 'ethnicity'],
      dtype='object')

,ee#,first_name,last_name,full_name,position,position_type,start_date,term_date,tenure,birth_date,age,department,dpt_acronym,work_location,employment_province,province_acronym,hire_source,level,gender,ethnicity
134392,10134392,Andrew,Anthony,"Anthony, Andrew",Director of Innovation,Full Time - Temporary,2002-07-31,2014-12-22,12.4,1950-10-04,64.2,Technology Solutions & Services,TSS,Surrey,British Columbia,BC,direct,Director,Man,Caucasian
1378451,11378451,Marilyn,Henry,"Henry, Marilyn",Account Manager,Full Time - Regular,1997-07-27,2000-03-01,2.6,1938-03-23,61.9,Client Experience & Engagement,CEE,Toronto,Ontario,ON,direct,Professional,Man,Asian
901122,10901122,Lindsay,Lee,"Lee, Lindsay",Communications Coordinator,Full Time - Regular,2009-06-12,2010-02-20,0.7,1952-02-18,58.0,Communications & Brand Strategy,CBS,Mississauga,Ontario,ON,direct,Support,Woman,Caucasian
1573289,11573289,David,Peterson,"Peterson, David",Marketing Communications Manager,Full Time - Regular,2001-06-29,None,24.3,1975-02-18,50.6,Communications & Brand Strategy,CBS,Burnaby,British Columbia,BC,referral,Professional,Woman,Caucasian
815592,10815592,Christopher,Johnson,"Johnson, Christopher",Director of Compliance,Full Time - Regular,2012-06-18,None,13.3,1977-08-20,48.1,Regulatory Compliance & Risk Management,RCRM,Charlottetown,Prince Edward Island,PE,direct,Director,Woman,Caucasian

## Assigning termination reasons according to specific weigths to simulate real data and train the model

In [14]:
# Define default termination reasons
perm_terms  = {
    "other": 0.2,
    "resignation": 0.5,
    "without cause": 0.2,
    "dismissal": 0.1
}

temp_terms  = {
    "end of contract": 0.8,
    "dismissal": 0.05,
    "resignation": 0.15
}

# Define higher resignation rates for specific conditions
pattern_perm_terms  = {
    "other": 0.025,
    "resignation": 0.8,
    "without cause": 0.15,
    "dismissal": 0.025
}

pattern_temp_terms  = {
    "end of contract": 0.6,
    "dismissal": 0.15,
    "resignation": 0.25
}

In [15]:
def assign_termination_reason(df, column, value):
    '''
    Assigns a termination reason to rows containing terminated EEs.
    Uses default termination reasons and weights unless certain conditions
    are met, in which case it uses the reasons and weights with higher 
    resignation rates.

    Input:
    df: a dataframe in which to add the termination reason column
    column: a column that contains a value that triggers the pattern
    value: the value that triggers the pattern

    Output:
    a dataframe with the added termination reason column
    '''
    # Create output column initialized as NaN
    df["term_reason"] = np.nan

    # Iterate over the DataFrame rows
    for idx, row in df.iterrows():
        term_date = row['term_date']
        ee_type = row['position_type']
        trigger = row[column]

        if pd.isna(term_date):
            continue  # Leave as NaN

        if ee_type in ["Full Time - Regular", "Part Time - Regular"]:
            if trigger == value:
                df.at[idx, "term_reason"] = random.choices(population= list(pattern_perm_terms.keys()),
                                                       weights= list(pattern_perm_terms.values()),
                                                       k= 1)[0]
            else:
                df.at[idx, "term_reason"] = random.choices(population= list(perm_terms.keys()),
                                                       weights= list(perm_terms.values()),
                                                       k= 1)[0]
        elif ee_type in ["Full Time - Temporary", "Part Time - Temporary"]:
            if trigger == value:
                df.at[idx, "term_reason"] = random.choices(population= list(pattern_temp_terms.keys()),
                                                       weights= list(pattern_temp_terms.values()),
                                                       k= 1)[0]
            else:
                df.at[idx, "term_reason"] = random.choices(population= list(temp_terms.keys()),
                                                       weights= list(temp_terms.values()),
                                                       k= 1)[0]
        # Otherwise remain NaN

    return df

Let's simulate a situation where resignations in `work_location = Regina` are higher than normal.

In [17]:
attrition_with_pattern = assign_termination_reason(df= attrition,
                                                   column= 'work_location',
                                                   value= 'Regina')
attrition_with_pattern.sample(5)

/var/folders/_5/2w3kvrj134g6p526z781sqxh0000gn/T/ipykernel_74078/58470599.py:34: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'without cause' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[idx, "term_reason"] = random.choices(population= list(perm_terms.keys()),

,ee#,first_name,last_name,full_name,position,position_type,start_date,term_date,tenure,birth_date,...,department,dpt_acronym,work_location,employment_province,province_acronym,hire_source,level,gender,ethnicity,term_reason
1820633,11820633,James,Dorsey,"Dorsey, James",Senior Analyst,Full Time - Regular,1999-10-14,None,26.0,1955-12-17,...,Portfolio Management & Execution,PME,Calgary,Alberta,AB,referral,Professional,Man,Caucasian,NaN
1900468,11900468,Melissa,Allen,"Allen, Melissa",Compliance Manager,Full Time - Regular,1985-06-26,1992-04-23,6.8,1926-01-16,...,Regulatory Compliance & Risk Management,RCRM,Burnaby,British Columbia,BC,agency,Professional,Woman,Caucasian,without cause
1384850,11384850,Jodi,Reynolds,"Reynolds, Jodi",Senior Analyst,Full Time - Regular,2019-01-31,None,6.7,1972-07-01,...,Portfolio Management & Execution,PME,Montreal,Quebec,QC,agency,Professional,Man,Caucasian,NaN
193831,10193831,Kathleen,Knight,"Knight, Kathleen",Service Delivery Manager,Full Time - Regular,2007-04-01,2012-11-16,5.6,1953-07-18,...,Service Delivery & Operations,SDO,Laval,Quebec,QC,agency,Professional,Man,Caucasian,resignation
1981336,11981336,Michael,Delgado,"Delgado, Michael",Regulatory Compliance Specialist,Full Time - Regular,2023-04-29,None,2.4,1994-03-03,...,Regulatory Compliance & Risk Management,RCRM,Winnipeg,Manitoba,MB,agency,Professional,Man,Caucasian,NaN

## Data check & Export

In [19]:
def deluxe_value_counts(df, column):
    counts = df[column].value_counts(dropna= False)
    percentages = df[column].value_counts(normalize= True, dropna= False).mul(100).round(1)
    deluxe_count = pd.concat([counts, percentages], axis= 1, keys= ['#', '%'])
    return deluxe_count

data_check = attrition_with_pattern[attrition_with_pattern['work_location'] == 'Regina']
deluxe_value_counts(data_check, 'term_reason')

                     #     %
term_reason
NaN              29347  48.9
resignation      24179  40.3
without cause     4530   7.5
dismissal          819   1.4
other              759   1.3
end of contract    399   0.7

Resignations are far more frequently than any other termination reason, so the dataframe is good to be exported.

In [21]:
# export the dataframe to .csv file
attrition_with_pattern.to_csv('attrition_df.csv', index= False)